import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import sear from "./services/sear";
import Storage from "./services/Storage";
import type { Todo } from "./models/Todo";
import * as React from "react";

import Button from "@mui/material/Button";
import { red } from "@material-ui/core/colors";
import { makeStyles, styled } from "@mui/styles";
import { Box, TextField } from "@mui/material";
const Home: NextPage = () => {
  const [token, setToken] = useState<Todo[]>([]);
  const [myvalue, setmyvalue] = useState("");
  useEffect(() => {
    async function getToken() {
      // await Storage.create('hi')
      const token = await Storage.all();
      setToken(token);
    }
    getToken();
  }, []);

  const deletes = async (data: number) => {
    await Storage.remove(data);
    const tokenss = await Storage.all();
    setToken((tockens) => [...([] as Todo[]), ...tokenss]);
  };
  const asyncFunc = async (data: string) => {
    // let promise = new Promise((resolve, reject) => {
    //     setTimeout(() => resolve("I am a done promise!"), 3000)
    // });

    // let result = await promise
    await Storage.create(myvalue);

    const d: Todo = { id: 900, title: myvalue, completed: true };
    const tokenss = await Storage.all();
    // setToken(tockens=>[...tockens,...tockens])
    setToken((tockens) => [...([] as Todo[]), ...tokenss]);

    // setToken(token)
    // alert(data);
  };
  const reds = red[500];

  const useStyles = makeStyles({
    root: {
      color: "white",
    },
  });

  const useStyless = makeStyles({
    root: {
      background: "linear-gradient(45deg, #FE6B8B 30%, #FF8E53 90%)",
      border: 0,
      borderRadius: 3,
      boxShadow: "0 3px 5px 2px rgba(255, 105, 135, .3)",
      color: "white",
      height: 48,
      padding: "0 30px",
    },
  });
  const MyButton = styled(Button)({
    background: "linear-gradient(45deg, #FE6B8B 30%, #FF8E53 90%)",
    border: 0,
    borderRadius: 3,
    boxShadow: "0 3px 5px 2px rgba(255, 105, 135, .3)",
    color: "white",
    height: 48,
    padding: "0 30px",
  });
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{
          height: "150px",
          display: "flex",
          flexDirection: "row",
          justifyContent: "center",
          flexWrap: "wrap",
          alignContent: "center",
        }}
      >
        <Box  marginRight="20px">
        <TextField
          value={myvalue}
          onChange={(e) => setmyvalue(e.target.value)}
          id="outlined-basic"
          label="Content"
          variant="outlined"
          
          
        /></Box>

        {/* <input
          value={myvalue}
          onChange={(e) => setmyvalue(e.target.value)}
          color="default"
        /> */}
        {/* <Button className={useStyless.root}>Styled with Hook API</Button>
        <MyButton>Styled Components</MyButton>; */}
        {/* <Box margin="20px" > */}
        <Button
        
          variant="contained"
          onClick={(e) => {
            asyncFunc(myvalue);
          }}
          type="submit"
        >
          Submit
        </Button>
        {/* </Box> */}
      </div>
      <ul>
        {token.map((x: Todo) => {
          return (
            <li>
              <div
                style={{
                  margin: "20px",
                  display: "flex",
                  flexDirection: "row",
                  justifyContent: "space-between",
                  flexWrap: "wrap",
                  alignContent: "center",
                }}
              >
                {x.title}{" "}
                <Button
                  color="error"
                  variant="contained"
                  onClick={(e) => deletes(x.id)}
                >
                  Delete
                </Button>
              </div>
            </li>
          );
        })}
      </ul>
      <main className={styles.main}></main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
