import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import sear from "./services/sear";
import Storage from "./services/Storage";
import type { Todo } from "./models/Todo";
const Home: NextPage = () => {
  const [token, setToken] = useState<Todo[]>([]);
  const [myvalue, setmyvalue] = useState("");
  useEffect(() => {
    async function getToken() {
      // await Storage.create('hi')
      const token = await Storage.all();
      setToken(token);
    }
    getToken();
  }, []);

  const deletes = async (data: number) => {
    await Storage.remove(data);
    const tokenss = await Storage.all();
    setToken((tockens) => [...([] as Todo[]), ...tokenss]);
  };
  const asyncFunc = async (data: string) => {
    // let promise = new Promise((resolve, reject) => {
    //     setTimeout(() => resolve("I am a done promise!"), 3000)
    // });

    // let result = await promise
    await Storage.create(myvalue);

    const d: Todo = { id: 900, title: myvalue, completed: true };
    const tokenss = await Storage.all();
    // setToken(tockens=>[...tockens,...tockens])
    setToken((tockens) => [...([] as Todo[]), ...tokenss]);

    // setToken(token)
    // alert(data);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{
          height: "150px",
          display: "flex",
          flexDirection: "row",
          justifyContent: "center",
          flexWrap: "wrap",
          alignContent: "center",
        }}
      >
        <input
          value={myvalue}
          onChange={(e) => setmyvalue(e.target.value)}
          color="default"
        />
        <button
          onClick={(e) => {
            asyncFunc(myvalue);
          }}
          type="submit"
        >
          Submit
        </button>
      </div>
      <ul>
        {token.map((x: Todo) => {
          return (
            <li>
              <div
                style={{
                  margin:"20px",
                  display: "flex",
                  flexDirection: "row",
                  justifyContent: "space-between",
                  flexWrap: "wrap",
                  alignContent: "center",
                }}
              >
                {x.title} <button onClick={(e) => deletes(x.id)}>Delete</button>
              </div>
            </li>
          );
        })}
      </ul>
      <main className={styles.main}></main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
